### ISSUE TITLE
Container app in docker failed to run due to missing docker_boot.sh

### ISSUE THREAD

**Issue by JustAPhrog** [range-of-motion/budget#369] opened 2022-07-22 07:48 UTC
**Expected behavior**

1. Clone repo
2. Run `docker-compose up -d` using Powershell on Windows 10.
3. 2 containers created and started

**Current behavior**

Container with database works fine but with app failed to run:

    /usr/local/bin/docker-php-entrypoint: 9: exec: ./docker_boot.sh: not found

When I changed command to `sleep 1000` and connect with bash to this I see that `docker_boot.sh` is present. Changing command to `/var/www/docker_boot.sh` not fix this.

I've cheked this in WSL Ubuntu by doing 1-3 steps - same error occurd.

**Enviroment**

    Docker Desktop 4.10.1 (82475)
    Current build from master (22.07.2022)

**Comment by range-of-motion** [comment] 2023-03-28 16:32
I've just tried this on a fresh clone of the repo, and I can't reproduce the error (on macOS at least). I understand it's nearly a year ago since you reported this, however if you're still up for it, I'm down to debug this with you. Either through here (the issue on GitHub) or the Discord.

**Comment by range-of-motion** [comment] 2023-10-21 22:43
Since this hasn't received a reply yet, I'm going to close this issue. Feel free to re-open it if the issue re-appears.

**Closed by range-of-motion** 2023-10-21 22:43 UTC
Labels: bug
